'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class boiler

    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''OPCWebRefresh1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OPCWebRefresh1 As Global.OPCWebControls.OPCWebRefresh

    '''<summary>
    '''OPCWebControlsLabel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OPCWebControlsLabel1 As Global.OPCWebControls.OPCWebControlsLabel

    '''<summary>
    '''OPCWebControlsLabel2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OPCWebControlsLabel2 As Global.OPCWebControls.OPCWebControlsLabel

    '''<summary>
    '''OPCWebControlsLabel3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OPCWebControlsLabel3 As Global.OPCWebControls.OPCWebControlsLabel

    '''<summary>
    '''OPCWebControlsLabel4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OPCWebControlsLabel4 As Global.OPCWebControls.OPCWebControlsLabel

    '''<summary>
    '''OPCWebControlsLabel5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OPCWebControlsLabel5 As Global.OPCWebControls.OPCWebControlsLabel

    '''<summary>
    '''OPCWebControlsLabel6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OPCWebControlsLabel6 As Global.OPCWebControls.OPCWebControlsLabel

    '''<summary>
    '''OPCWebControlsLabel7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OPCWebControlsLabel7 As Global.OPCWebControls.OPCWebControlsLabel

    '''<summary>
    '''OPCWebControlsLabel8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OPCWebControlsLabel8 As Global.OPCWebControls.OPCWebControlsLabel

    '''<summary>
    '''OPCWebControlsLabel9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OPCWebControlsLabel9 As Global.OPCWebControls.OPCWebControlsLabel

    '''<summary>
    '''OPCWebControlsLabel10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OPCWebControlsLabel10 As Global.OPCWebControls.OPCWebControlsLabel

    '''<summary>
    '''OPCWebControlsLabel11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OPCWebControlsLabel11 As Global.OPCWebControls.OPCWebControlsLabel

    '''<summary>
    '''OPCWebControlsLabel12 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OPCWebControlsLabel12 As Global.OPCWebControls.OPCWebControlsLabel

    '''<summary>
    '''OPCWebControlsLabel13 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OPCWebControlsLabel13 As Global.OPCWebControls.OPCWebControlsLabel

    '''<summary>
    '''OPCWebControlsLabel14 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OPCWebControlsLabel14 As Global.OPCWebControls.OPCWebControlsLabel

    '''<summary>
    '''OPCWebControlsLabel15 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OPCWebControlsLabel15 As Global.OPCWebControls.OPCWebControlsLabel

    '''<summary>
    '''OPCWebControlsLabel16 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OPCWebControlsLabel16 As Global.OPCWebControls.OPCWebControlsLabel

    '''<summary>
    '''OPCWebControlsLabel17 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OPCWebControlsLabel17 As Global.OPCWebControls.OPCWebControlsLabel

    '''<summary>
    '''OPCWebControlsLabel18 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OPCWebControlsLabel18 As Global.OPCWebControls.OPCWebControlsLabel

    '''<summary>
    '''OPCWebControlsLabel19 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OPCWebControlsLabel19 As Global.OPCWebControls.OPCWebControlsLabel

    '''<summary>
    '''OPCWebControlsLabel20 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OPCWebControlsLabel20 As Global.OPCWebControls.OPCWebControlsLabel

    '''<summary>
    '''OPCWebControlsLabel21 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OPCWebControlsLabel21 As Global.OPCWebControls.OPCWebControlsLabel

    '''<summary>
    '''OPCWebControlsLabel22 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OPCWebControlsLabel22 As Global.OPCWebControls.OPCWebControlsLabel

    '''<summary>
    '''OPCWebControlsLabel23 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OPCWebControlsLabel23 As Global.OPCWebControls.OPCWebControlsLabel

    '''<summary>
    '''OPCWebControlsLabel24 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OPCWebControlsLabel24 As Global.OPCWebControls.OPCWebControlsLabel

    '''<summary>
    '''OPCWebControlsLabel25 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OPCWebControlsLabel25 As Global.OPCWebControls.OPCWebControlsLabel

    '''<summary>
    '''OPCWebControlsLabel26 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OPCWebControlsLabel26 As Global.OPCWebControls.OPCWebControlsLabel

    '''<summary>
    '''OPCWebControlsLabel27 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OPCWebControlsLabel27 As Global.OPCWebControls.OPCWebControlsLabel

    '''<summary>
    '''OPCWebControlsLabel28 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OPCWebControlsLabel28 As Global.OPCWebControls.OPCWebControlsLabel

    '''<summary>
    '''OPCWebControlsLabel29 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OPCWebControlsLabel29 As Global.OPCWebControls.OPCWebControlsLabel

    '''<summary>
    '''OPCWebControlsLabel30 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OPCWebControlsLabel30 As Global.OPCWebControls.OPCWebControlsLabel

    '''<summary>
    '''OPCWebControlsLabel31 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OPCWebControlsLabel31 As Global.OPCWebControls.OPCWebControlsLabel

    '''<summary>
    '''OPCWebControlsLabel32 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OPCWebControlsLabel32 As Global.OPCWebControls.OPCWebControlsLabel

    '''<summary>
    '''OPCWebControlsLabel33 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OPCWebControlsLabel33 As Global.OPCWebControls.OPCWebControlsLabel

    '''<summary>
    '''OPCWebControlsLabel34 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OPCWebControlsLabel34 As Global.OPCWebControls.OPCWebControlsLabel

    '''<summary>
    '''OPCWebControlsLabel35 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OPCWebControlsLabel35 As Global.OPCWebControls.OPCWebControlsLabel

    '''<summary>
    '''OPCWebControlsLabel36 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OPCWebControlsLabel36 As Global.OPCWebControls.OPCWebControlsLabel

    '''<summary>
    '''OPCWebControlsLabel37 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OPCWebControlsLabel37 As Global.OPCWebControls.OPCWebControlsLabel

    '''<summary>
    '''OPCWebControlsLabel38 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OPCWebControlsLabel38 As Global.OPCWebControls.OPCWebControlsLabel

    '''<summary>
    '''OPCWebControlsLabel39 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OPCWebControlsLabel39 As Global.OPCWebControls.OPCWebControlsLabel

    '''<summary>
    '''OPCWebControlsLabel40 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OPCWebControlsLabel40 As Global.OPCWebControls.OPCWebControlsLabel

    '''<summary>
    '''OPCWebControlsLabel41 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OPCWebControlsLabel41 As Global.OPCWebControls.OPCWebControlsLabel

    '''<summary>
    '''OPCWebControlsLabel42 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OPCWebControlsLabel42 As Global.OPCWebControls.OPCWebControlsLabel

    '''<summary>
    '''OPCWebControlsLabel43 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OPCWebControlsLabel43 As Global.OPCWebControls.OPCWebControlsLabel

    '''<summary>
    '''OPCWebControlsLabel44 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OPCWebControlsLabel44 As Global.OPCWebControls.OPCWebControlsLabel

    '''<summary>
    '''OPCWebControlsLabel45 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OPCWebControlsLabel45 As Global.OPCWebControls.OPCWebControlsLabel

    '''<summary>
    '''OPCWebControlsLabel46 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OPCWebControlsLabel46 As Global.OPCWebControls.OPCWebControlsLabel

    '''<summary>
    '''OPCWebControlsLabel47 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OPCWebControlsLabel47 As Global.OPCWebControls.OPCWebControlsLabel

    '''<summary>
    '''OPCWebControlsLabel48 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OPCWebControlsLabel48 As Global.OPCWebControls.OPCWebControlsLabel

    '''<summary>
    '''OPCWebControlsLabel49 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OPCWebControlsLabel49 As Global.OPCWebControls.OPCWebControlsLabel

    '''<summary>
    '''OPCWebControlsLabel50 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OPCWebControlsLabel50 As Global.OPCWebControls.OPCWebControlsLabel

    '''<summary>
    '''OPCWebControlsLabel51 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OPCWebControlsLabel51 As Global.OPCWebControls.OPCWebControlsLabel

    '''<summary>
    '''OPCWebControlsLabel52 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OPCWebControlsLabel52 As Global.OPCWebControls.OPCWebControlsLabel

    '''<summary>
    '''OPCWebControlsLabel53 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OPCWebControlsLabel53 As Global.OPCWebControls.OPCWebControlsLabel

    '''<summary>
    '''OPCWebControlsLabel54 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OPCWebControlsLabel54 As Global.OPCWebControls.OPCWebControlsLabel

    '''<summary>
    '''OPCWebControlsLabel55 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OPCWebControlsLabel55 As Global.OPCWebControls.OPCWebControlsLabel

    '''<summary>
    '''OPCWebControlsLabel56 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OPCWebControlsLabel56 As Global.OPCWebControls.OPCWebControlsLabel

    '''<summary>
    '''OPCWebControlsLabel57 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OPCWebControlsLabel57 As Global.OPCWebControls.OPCWebControlsLabel

    '''<summary>
    '''OPCWebControlsLabel58 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OPCWebControlsLabel58 As Global.OPCWebControls.OPCWebControlsLabel

    '''<summary>
    '''OPCWebControlsLabel59 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OPCWebControlsLabel59 As Global.OPCWebControls.OPCWebControlsLabel

    '''<summary>
    '''OPCWebControlsLabel60 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OPCWebControlsLabel60 As Global.OPCWebControls.OPCWebControlsLabel

    '''<summary>
    '''OPCWebControlsLabel61 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OPCWebControlsLabel61 As Global.OPCWebControls.OPCWebControlsLabel

    '''<summary>
    '''OPCWebControlsLabel62 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OPCWebControlsLabel62 As Global.OPCWebControls.OPCWebControlsLabel

    '''<summary>
    '''OPCWebControlsLabel63 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OPCWebControlsLabel63 As Global.OPCWebControls.OPCWebControlsLabel

    '''<summary>
    '''OPCWebControlsLabel64 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OPCWebControlsLabel64 As Global.OPCWebControls.OPCWebControlsLabel

    '''<summary>
    '''OPCWebControlsLabel65 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OPCWebControlsLabel65 As Global.OPCWebControls.OPCWebControlsLabel

    '''<summary>
    '''OPCWebControlsLabel66 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OPCWebControlsLabel66 As Global.OPCWebControls.OPCWebControlsLabel

    '''<summary>
    '''OPCWebControlsLabel67 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OPCWebControlsLabel67 As Global.OPCWebControls.OPCWebControlsLabel

    '''<summary>
    '''OPCWebControlsLabel68 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OPCWebControlsLabel68 As Global.OPCWebControls.OPCWebControlsLabel

    '''<summary>
    '''OPCWebControlsLabel69 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OPCWebControlsLabel69 As Global.OPCWebControls.OPCWebControlsLabel

    '''<summary>
    '''OPCWebControlsLabel70 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OPCWebControlsLabel70 As Global.OPCWebControls.OPCWebControlsLabel

    '''<summary>
    '''OPCWebControlsLabel71 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OPCWebControlsLabel71 As Global.OPCWebControls.OPCWebControlsLabel

    '''<summary>
    '''OPCWebControlsLabel72 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OPCWebControlsLabel72 As Global.OPCWebControls.OPCWebControlsLabel

    '''<summary>
    '''OPCWebControlsLabel73 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OPCWebControlsLabel73 As Global.OPCWebControls.OPCWebControlsLabel

    '''<summary>
    '''OPCWebControlsLabel74 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OPCWebControlsLabel74 As Global.OPCWebControls.OPCWebControlsLabel

    '''<summary>
    '''OPCWebControlsLabel75 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OPCWebControlsLabel75 As Global.OPCWebControls.OPCWebControlsLabel

    '''<summary>
    '''OPCWebControlsLabel76 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OPCWebControlsLabel76 As Global.OPCWebControls.OPCWebControlsLabel

    '''<summary>
    '''OPCWebControlsLabel77 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OPCWebControlsLabel77 As Global.OPCWebControls.OPCWebControlsLabel

    '''<summary>
    '''OPCWebControlsLabel78 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OPCWebControlsLabel78 As Global.OPCWebControls.OPCWebControlsLabel

    '''<summary>
    '''OPCWebControlsLabel79 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OPCWebControlsLabel79 As Global.OPCWebControls.OPCWebControlsLabel

    '''<summary>
    '''OPCWebControlsLabel80 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OPCWebControlsLabel80 As Global.OPCWebControls.OPCWebControlsLabel

    '''<summary>
    '''OPCWebControlsLabel81 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OPCWebControlsLabel81 As Global.OPCWebControls.OPCWebControlsLabel

    '''<summary>
    '''OPCWebControlsLabel82 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OPCWebControlsLabel82 As Global.OPCWebControls.OPCWebControlsLabel

    '''<summary>
    '''OPCWebControlsLabel83 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OPCWebControlsLabel83 As Global.OPCWebControls.OPCWebControlsLabel

    '''<summary>
    '''OPCWebControlsLabel84 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OPCWebControlsLabel84 As Global.OPCWebControls.OPCWebControlsLabel

    '''<summary>
    '''OPCWebControlsLabel85 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OPCWebControlsLabel85 As Global.OPCWebControls.OPCWebControlsLabel

    '''<summary>
    '''OPCWebControlsLabel86 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OPCWebControlsLabel86 As Global.OPCWebControls.OPCWebControlsLabel

    '''<summary>
    '''OPCWebControlsLabel87 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OPCWebControlsLabel87 As Global.OPCWebControls.OPCWebControlsLabel

    '''<summary>
    '''OPCWebControlsLabel88 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OPCWebControlsLabel88 As Global.OPCWebControls.OPCWebControlsLabel

    '''<summary>
    '''OPCWebControlsLabel89 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OPCWebControlsLabel89 As Global.OPCWebControls.OPCWebControlsLabel

    '''<summary>
    '''OPCWebControlsLabel90 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OPCWebControlsLabel90 As Global.OPCWebControls.OPCWebControlsLabel

    '''<summary>
    '''OPCWebControlsLabel91 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OPCWebControlsLabel91 As Global.OPCWebControls.OPCWebControlsLabel

    '''<summary>
    '''OPCWebControlsLabel92 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OPCWebControlsLabel92 As Global.OPCWebControls.OPCWebControlsLabel

    '''<summary>
    '''OPCWebControlsLabel93 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OPCWebControlsLabel93 As Global.OPCWebControls.OPCWebControlsLabel

    '''<summary>
    '''OPCWebControlsLabel94 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OPCWebControlsLabel94 As Global.OPCWebControls.OPCWebControlsLabel

    '''<summary>
    '''OPCWebControlsLabel95 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OPCWebControlsLabel95 As Global.OPCWebControls.OPCWebControlsLabel

    '''<summary>
    '''OPCWebControlsLabel96 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OPCWebControlsLabel96 As Global.OPCWebControls.OPCWebControlsLabel

    '''<summary>
    '''OPCWebControlsLabel97 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OPCWebControlsLabel97 As Global.OPCWebControls.OPCWebControlsLabel

    '''<summary>
    '''OPCWebControlsLabel98 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OPCWebControlsLabel98 As Global.OPCWebControls.OPCWebControlsLabel

    '''<summary>
    '''OPCWebControlsLabel99 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OPCWebControlsLabel99 As Global.OPCWebControls.OPCWebControlsLabel

    '''<summary>
    '''OPCWebControlsLabel100 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OPCWebControlsLabel100 As Global.OPCWebControls.OPCWebControlsLabel

    '''<summary>
    '''OPCWebControlsLabel101 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OPCWebControlsLabel101 As Global.OPCWebControls.OPCWebControlsLabel

    '''<summary>
    '''OPCWebControlsLabel102 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OPCWebControlsLabel102 As Global.OPCWebControls.OPCWebControlsLabel

    '''<summary>
    '''OPCWebControlsLabel103 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OPCWebControlsLabel103 As Global.OPCWebControls.OPCWebControlsLabel

    '''<summary>
    '''OPCWebControlsLabel104 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OPCWebControlsLabel104 As Global.OPCWebControls.OPCWebControlsLabel

    '''<summary>
    '''OPCWebControlsLabel105 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OPCWebControlsLabel105 As Global.OPCWebControls.OPCWebControlsLabel

    '''<summary>
    '''OPCWebControlsLabel106 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OPCWebControlsLabel106 As Global.OPCWebControls.OPCWebControlsLabel

    '''<summary>
    '''OPCWebControlsLabel107 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OPCWebControlsLabel107 As Global.OPCWebControls.OPCWebControlsLabel

    '''<summary>
    '''OPCWebControlsLabel108 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OPCWebControlsLabel108 As Global.OPCWebControls.OPCWebControlsLabel

    '''<summary>
    '''OPCWebControlsLabel109 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OPCWebControlsLabel109 As Global.OPCWebControls.OPCWebControlsLabel

    '''<summary>
    '''OPCWebControlsLabel110 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OPCWebControlsLabel110 As Global.OPCWebControls.OPCWebControlsLabel

    '''<summary>
    '''OPCWebControlsLabel111 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OPCWebControlsLabel111 As Global.OPCWebControls.OPCWebControlsLabel

    '''<summary>
    '''OPCWebControlsLabel112 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OPCWebControlsLabel112 As Global.OPCWebControls.OPCWebControlsLabel
End Class
