'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class home

    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''OPCWebRefresh1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OPCWebRefresh1 As Global.OPCWebControls.OPCWebRefresh

    '''<summary>
    '''OPCWebControlsLabel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OPCWebControlsLabel1 As Global.OPCWebControls.OPCWebControlsLabel

    '''<summary>
    '''OPCWebControlsLabel2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OPCWebControlsLabel2 As Global.OPCWebControls.OPCWebControlsLabel

    '''<summary>
    '''OPCWebControlsLabel3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OPCWebControlsLabel3 As Global.OPCWebControls.OPCWebControlsLabel

    '''<summary>
    '''OPCWebControlsLabel4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OPCWebControlsLabel4 As Global.OPCWebControls.OPCWebControlsLabel

    '''<summary>
    '''OPCWebControlsLabel5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OPCWebControlsLabel5 As Global.OPCWebControls.OPCWebControlsLabel

    '''<summary>
    '''OPCWebControlsLabel6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OPCWebControlsLabel6 As Global.OPCWebControls.OPCWebControlsLabel

    '''<summary>
    '''OPCWebControlsLabel7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OPCWebControlsLabel7 As Global.OPCWebControls.OPCWebControlsLabel

    '''<summary>
    '''OPCWebControlsLabel8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OPCWebControlsLabel8 As Global.OPCWebControls.OPCWebControlsLabel

    '''<summary>
    '''OPCWebControlsLabel9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OPCWebControlsLabel9 As Global.OPCWebControls.OPCWebControlsLabel

    '''<summary>
    '''OPCWebControlsLabel10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OPCWebControlsLabel10 As Global.OPCWebControls.OPCWebControlsLabel

    '''<summary>
    '''OPCWebControlsLabel11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OPCWebControlsLabel11 As Global.OPCWebControls.OPCWebControlsLabel

    '''<summary>
    '''OPCWebControlsLabel12 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OPCWebControlsLabel12 As Global.OPCWebControls.OPCWebControlsLabel

    '''<summary>
    '''OPCWebControlsLabel13 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OPCWebControlsLabel13 As Global.OPCWebControls.OPCWebControlsLabel

    '''<summary>
    '''OPCWebControlsLabel14 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OPCWebControlsLabel14 As Global.OPCWebControls.OPCWebControlsLabel

    '''<summary>
    '''OPCWebControlsLabel15 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OPCWebControlsLabel15 As Global.OPCWebControls.OPCWebControlsLabel

    '''<summary>
    '''OPCWebControlsLabel16 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OPCWebControlsLabel16 As Global.OPCWebControls.OPCWebControlsLabel

    '''<summary>
    '''OPCWebControlsLabel17 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OPCWebControlsLabel17 As Global.OPCWebControls.OPCWebControlsLabel

    '''<summary>
    '''OPCWebControlsLabel18 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OPCWebControlsLabel18 As Global.OPCWebControls.OPCWebControlsLabel

    '''<summary>
    '''OPCWebControlsLabel19 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OPCWebControlsLabel19 As Global.OPCWebControls.OPCWebControlsLabel

    '''<summary>
    '''OPCWebControlsLabel20 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OPCWebControlsLabel20 As Global.OPCWebControls.OPCWebControlsLabel

    '''<summary>
    '''OPCWebControlsLabel21 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OPCWebControlsLabel21 As Global.OPCWebControls.OPCWebControlsLabel

    '''<summary>
    '''OPCWebControlsLabel22 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OPCWebControlsLabel22 As Global.OPCWebControls.OPCWebControlsLabel

    '''<summary>
    '''OPCWebControlsLabel23 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OPCWebControlsLabel23 As Global.OPCWebControls.OPCWebControlsLabel

    '''<summary>
    '''OPCWebControlsLabel24 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OPCWebControlsLabel24 As Global.OPCWebControls.OPCWebControlsLabel

    '''<summary>
    '''OPCWebControlsLabel25 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OPCWebControlsLabel25 As Global.OPCWebControls.OPCWebControlsLabel

    '''<summary>
    '''OPCWebControlsLabel26 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OPCWebControlsLabel26 As Global.OPCWebControls.OPCWebControlsLabel

    '''<summary>
    '''OPCWebControlsLabel27 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OPCWebControlsLabel27 As Global.OPCWebControls.OPCWebControlsLabel

    '''<summary>
    '''OPCWebControlsLabel28 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OPCWebControlsLabel28 As Global.OPCWebControls.OPCWebControlsLabel
End Class
